services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: rust_time_communication_hub
    ports: 
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rust_time_communication_hub
    ports: 
      - 3307:3306
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: rust_time_communication_hub
    ports: 
      - 5432:5432