CREATE TABLE "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "external_id" varchar(255) UNIQUE NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "group" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(255) UNIQUE NOT NULL
);

CREATE TABLE "message" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "payload" varchar(255) NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "user_message" (
  "user_id" integer NOT NULL,
  "message_id" integer NOT NULL,
  "read" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("user_id", "message_id"),
  FOREIGN KEY ("user_id") REFERENCES "user" ("id"),
  FOREIGN KEY ("message_id") REFERENCES "message" ("id")
);

CREATE TABLE "user_group" (
  "user_id" integer NOT NULL,
  "group_id" integer NOT NULL,
  PRIMARY KEY ("user_id", "group_id"),
  FOREIGN KEY ("user_id") REFERENCES "user" ("id"),
  FOREIGN KEY ("group_id") REFERENCES "group" ("id")
);
